name: CI Status

on:
  schedule:
  - cron: "*/8 * * * *"

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - uses: BluezTestBot/action-ci-status@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
